# Generated by Django 2.1.7 on 2019-03-28 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_auto_20190328_0807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='preview',
        ),
        migrations.AddField(
            model_name='poster',
            name='preview',
            field=models.ImageField(default=1, upload_to='image/preview/poster'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='file',
            field=models.FileField(default=1, upload_to='video'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='preview_img',
            field=models.ImageField(default=1, upload_to='image/preview/video'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='resources',
            field=models.FileField(upload_to='document/Courses/resourses'),
        ),
        migrations.AlterField(
            model_name='coursesession',
            name='resources',
            field=models.FileField(upload_to='document/Courses/resourses'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='image',
            field=models.ImageField(upload_to='image/poster'),
        ),
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.ImageField(upload_to='images/video'),
        ),
    ]
