# Generated by Django 2.1.7 on 2019-04-01 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0009_auto_20190330_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='format',
            new_name='formatted',
        ),
        migrations.AlterField(
            model_name='course',
            name='holding_date',
            field=models.DateField(default=datetime.date(2019, 4, 1)),
        ),
    ]
