# Generated by Django 2.1.7 on 2019-04-01 19:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0010_auto_20190401_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesession',
            name='file',
            field=models.FileField(default=1986, upload_to='course/session'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='holding_date',
            field=models.DateField(default=datetime.date(2019, 4, 2)),
        ),
        migrations.AlterField(
            model_name='coursesession',
            name='time',
            field=models.IntegerField(),
        ),
    ]
