# Generated by Django 2.1.7 on 2019-04-03 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0011_auto_20190402_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='holding_date',
            field=models.DateField(default=datetime.date(2019, 4, 3)),
        ),
    ]
