# Generated by Django 2.1.7 on 2019-04-03 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0012_auto_20190403_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursesession',
            old_name='Course',
            new_name='course',
        ),
    ]
