# Generated by Django 2.2.3 on 2019-07-10 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0014_auto_20190403_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='holding_date',
            field=models.DateField(default=datetime.date(2019, 7, 10)),
        ),
    ]
