# Generated by Django 2.2.3 on 2019-09-18 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0015_auto_20190710_2121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='image',
            new_name='تصویر',
        ),
        migrations.AlterField(
            model_name='course',
            name='holding_date',
            field=models.DateField(default=datetime.date(2019, 9, 18)),
        ),
    ]
